<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search phongban
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["phongban/new", "Create phongban"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "phongban/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $phongban): ?>
            <tr>
                <td><?php echo $phongban->id ?></td>
                <td><?php echo $phongban->name ?></td>

                <td><?php echo $this->tag->linkTo(["phongban/edit/" . $phongban->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["phongban/delete/" . $phongban->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("phongban/index", "First") ?></li>
                <li><?php echo $this->tag->linkTo("phongban/index?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("phongban/index?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("phongban/index?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>